export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOAD_ACCOUNTS = "LOAD_ACCOUNTS";
export const LOCK_ACCOUNT = "LOCK_ACCOUNT";
export const LOAD_RECEIVERS = "LOAD_RECEIVERS";
export const ADD_RECEIVERS = "ADD_RECEIVERS";
export const LOAD_TRANSACTIONS = "LOAD_TRANSACTIONS";
export const LOAD_TRANSACTION_BY_ID = "LOAD_TRANSACTION_BY_ID"
